name: test_vae_experiment

trainer:
  class: VAETrainer
  module: trainers.vae_trainer
  config:
    random_seed: 1111
    archive_dir: ./archives
    checkpoint_n_epochs: 10
    track_agent_quality: true
    reeval_archive: true
    grad_clip: true
    train_batch_size: 64
    test_batch_size: 64
    num_epochs: 300
    center_data: true
    conditional: false
    kl_coef: 0.000001
    amp:
      enabled: false

model:
  class: HypernetAutoEncoder
  module: autoencoders.hypernet
  config:
    emb_channels: 4
    z_channels: 4
    z_height: 4
    ghn_hid: 64
    obsnorm_hid: 64
    enc_fc_hid: 64


optim:
  class: Adam
  module: torch.optim
  config:
    lr: 0.0001

env:
  env_name: humanoid
  clip_obs_rew: true