name: test_experiment

trainer:
  class: PolicyDiffusion
  module: trainers.diffusion_trainer
  config:
    random_seed: 1111
    archive_dir: ./archives
    checkpoint_n_epochs: 10
    track_agent_quality: true
    use_language: false
    use_wandb: true
    debug: false
    reeval_archive: true
    grad_clip: true
    train_batch_size: 64
    test_batch_size: 64
    num_epochs: 300
    center_data: true
    autoencoder_cp_dir: results/debug_vae/
    amp:
      enabled: false


sampler:
  class: DDIMSampler
  module: samplers.ddim
  config:
    n_steps: 100

model:
  class: ConditionalUNet
  module: models.cond_unet
  config:
    in_channels: 4  # must be same as emb_channels
    out_channels: 4  # same ^
    channels: 64  # first conv layer projects to this dimensionality
    n_res_blocks: 1
    attention_levels: []
    channel_multipliers: [1, 2, 4]
    n_heads: 4
    d_cond: 256
    measure_dim: 2

optim:
  class: AdamW
  module: torch.optim
  config:
    lr: 0.001

env:
  env_name: humanoid
  clip_obs_rew: true

